const fs = require("fs-extra");
const path = require("path");
const { logSuccess } = require("./logMessage");

exports.generateRobotsTxt = async function (sitemapUrl) {
  let robotsTxtData =
    "# Generated by ap-ssg (Static Site Generator)\n" +
    "# Allow all web crawlers to access all pages\n" +
    "User-agent: *\n" +
    "Disallow:\n";

  robotsTxtData += `\nSitemap: ${sitemapUrl}\n`;

  const buildDir = path.join(process.cwd(), "build");
  const robotsTxtPath = path.join(buildDir, "robots.txt");

  await fs.ensureDir(buildDir);
  await fs.writeFile(robotsTxtPath, robotsTxtData);

  logSuccess(`robots.txt has been generated at: ${robotsTxtPath}`);
};
